{{- if .Values.explorer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "explorer.gui-name" . }}
  labels:
    app: {{ include "explorer.gui-name" . }}
spec:
  replicas: {{ .Values.api.replicas }}
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ include "explorer.gui-name" . }}
  template:
    metadata:
      labels:
        app: {{ include "explorer.gui-name" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ include "explorer.gui-name" . }}
        image: {{ .Values.explorer.gui.image.repo }}:{{ .Values.explorer.gui.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: endpoint
          containerPort: {{ .Values.explorer.gui.port }}
        {{ if ne .Values.environment "ci" }}
        resources:
{{ toYaml .Values.explorer.gui.resources | indent 10 }}
        {{ end }}
        env:
{{ include "explorer.gui-env" . | indent 8 }}
{{- end }}
