apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harvester.api-name" . }}
  labels:
    app: {{ include "harvester.api-name" . }}
spec:
  replicas: {{ .Values.api.replicas }}
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ include "harvester.api-name" . }}
  template:
    metadata:
      labels:
        app: {{ include "harvester.api-name" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: wait-for-mariadb
        image: mysql
        command: ["/bin/sh"]
        args:
        - -c
        - while ! mysqladmin ping -h"{{ .Values.db.host }}" --protocol=tcp -u "${DB_USERNAME}" -p"${DB_PASSWORD}" --silent; do sleep 3; done;
        env:
{{ include "harvester.api-worker-env" . | indent 8 }}
      - name: run-migrations
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        command: ["/bin/sh"]
        args:
        - -c
        - export PYTHONPATH=/usr/src/app:/usr/src/app/py-substrate-interface/:/usr/src/app/py-scale-codec/:$PYTHONPATH;
          alembic upgrade head
        env:
{{ include "harvester.api-worker-env" . | indent 8 }}
      containers:
      - name: {{ include "harvester.api-name" . }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: endpoint
          containerPort: {{ .Values.port }}
        readinessProbe:
          httpGet:
            path: /status
            port: {{ .Values.port }}
          initialDelaySeconds: 20
          timeoutSeconds: 200
        {{ if ne .Values.environment "ci" }}
        resources:
{{ toYaml .Values.api.resources | indent 10 }}
        {{ end }}
        env:
{{ include "harvester.api-worker-env" . | indent 8 }}
