apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  db-user: {{ .Values.db.name | b64enc }}
  db-password: {{ .Values.db.password | b64enc }}
