{{- if .Values.explorer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "explorer.gui-name" . }}
  labels:
    app: {{ include "explorer.gui-name" . }}
spec:
  ports:
  - name: endpoint
    port: {{ .Values.explorer.gui.port }}
  selector:
    app: {{ include "explorer.gui-name" . }}
{{- end }}
