environment: production

image:
  repo: web3f/harvester
  tag: latest

db:
  name: test
  host: mariadb
  port: 3306
  user: user
  password: pass

polkadotRPC: "http://polkadot:9933"

port: 8000

resources:
  limits:
    cpu: 200m
    memory: 900Mi
  requests:
    cpu: 200m
    memory: 900Mi

celery:
  broker: "redis://harvester-redis:6379/0"
  backend: "redis://harvester-redis:6379/0"

substrate:
  addressType: 2
  metadataVersion: 9

typeRegistry: kusama

api:
  replicas: 1
  resources: {}
worker:
  startCronjob:
    enabled: false
    schedule: "*/15 * * * *"
  replicas: 1
  resources: {}
beat:
  replicas: 1
  resources: {}

explorer:
  enabled: false
  api:
    port: 8080
    image:
      repo: polkascan/pre-explorer-api
      tag: latest
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
  gui:
    port: 80
    image:
      repo: polkascan/pre-explorer-gui
      tag: latest
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi

networkToken:
  symbol: KSM
  decimals: "12"
