environments:
  production:
  ci:

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: mariadb
  namespace: harvester
  chart: bitnami/mariadb
  version: 7.6.1
  values:
  - ./config/mariadb.yaml.gotmpl
