environments:
  production:
  ci:

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: redis
  namespace: harvester
  chart: bitnami/redis
  values:
  - ./config/redis.yaml.gotmpl
